version: '3.8'

services:
  loandb:
    image: postgres:14.1-alpine
    container_name: loandb
    restart: always
    environment:
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - loandb:/var/lib/loandb/postgresql/data

volumes:
  loandb:
    driver: local